spring.data.mongodb.uri=mongodb+srv://manickmanick37_db_user:9F28HiGkFm4k6Rpq@cluster0.ee2n9b6.mongodb.net/expenseTracker?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.database=expenseTracker

server.port=8080

# JWT Auth property
jwt.secret=ThisIsASecretKeyForJwtAuthenticationWhichShouldBeAtLeast256BitsLongForHmacSha256Algorithm
jwt.expirationMs=86400000

spring.mvc.pathmatch.matching-strategy=ant_path_matcher
