spring.data.mongodb.uri=mongodb+srv://2315050pk:Kathirvel%402005@placement-feedback-clus.y5zwxep.mongodb.net/focusroom?appName=placement-feedback-cluster
spring.data.mongodb.database=expenseTracker

server.port=8080

# JWT Auth property
jwt.secret=ThisIsASecretKeyForJwtAuthenticationWhichShouldBeAtLeast256BitsLongForHmacSha256Algorithm
jwt.expirationMs=86400000

spring.mvc.pathmatch.matching-strategy=ant_path_matcher
